apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-12-10T06:13:30Z"
  labels:
    app: prometheus-postgres-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-postgres-exporter-3.3.0
    heritage: Helm
    release: my-release
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:ports: {}
        f:selector:
          .: {}
          f:app: {}
          f:release: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: helm
    operation: Update
    time: "2022-12-10T06:13:30Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalIPs: {}
        f:ports:
          k:{"port":8880,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
    manager: agent
    operation: Update
    time: "2022-12-10T06:29:35Z"
  name: my-release-prometheus-postgres-exporter
  namespace: default
  resourceVersion: "10185428"
  uid: dec73266-e48f-4be9-b647-a9d0b01de03d
spec:
  clusterIP: 10.106.60.139
  clusterIPs:
  - 10.106.60.139
  externalIPs:
  - 172.16.4.247
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8880
    protocol: TCP
    targetPort: 9187
  selector:
    app: prometheus-postgres-exporter
    release: my-release
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

